### ISSUE TITLE
Text invades QR code (Sugarchain)

### ISSUE THREAD

**Issue by cryptozeny** [nao20010128nao/WalletGenerator.net#6]
![image](https://user-images.githubusercontent.com/37016180/65391523-1d27ca00-dda5-11e9-98aa-999cdee83603.png)

I think bech32 QR size is bigger than before. could you move the text a bit?

![image](https://user-images.githubusercontent.com/37016180/65391549-798ae980-dda5-11e9-84ce-35a959a7dee2.png)

**Comment by cryptozeny** [comment]
another position suggest
![image](https://user-images.githubusercontent.com/37016180/65391612-22d1df80-dda6-11e9-9a65-a64469334237.png)

**Comment by nao20010128nao** [comment]
How about removing `SHARE` and `SECRET` and coloring titles (`Public Address` and `Private Key (Wallet Import Format)`) respectively?    
Because `main.css` uses `position: relative;` for them, it's difficult to adjust. (at least for me, designers may do it better I think)

**Comment by cryptozeny** [comment]
yep it seems a good solution. bigger colorized font. (red and green)

**Comment by nao20010128nao** [comment]
probably fixed, currently have no problem with SegWit address

**Comment by cryptozeny** [comment]
i can confirm fixed! awesome!
