### ISSUE TITLE
Testing QR code on Printed Paperwallet

### ISSUE THREAD

**Issue by cryptozeny** [nao20010128nao/WalletGenerator.net#9]
# printed on A4 paper (portrait scale)
its working as expected.

![image](https://user-images.githubusercontent.com/37016180/66033537-711f7500-e542-11e9-9cb4-2d9ab8ed0350.png)

### QR Public
![image](https://user-images.githubusercontent.com/37016180/66033578-84324500-e542-11e9-85e5-fa20fb418645.png)

### Scan Public
![image](https://user-images.githubusercontent.com/37016180/66033606-8eecda00-e542-11e9-8eec-9443170dd353.png)

### QR Secret
![image](https://user-images.githubusercontent.com/37016180/66033662-acba3f00-e542-11e9-83fe-624b0a00ac2c.png)

### Scan Secret
![image](https://user-images.githubusercontent.com/37016180/66033682-b8a60100-e542-11e9-8022-0e17766f2d7d.png)

**Comment by cryptozeny** [comment]
# Printed on A4 (Landscape)
![image](https://user-images.githubusercontent.com/37016180/66034640-944b2400-e544-11e9-81e0-a1c07c055ae3.png)

QRapp: QR code Reader by TinyLab
Camera: iPhone6sPlus

### Public
![image](https://user-images.githubusercontent.com/37016180/66034589-7da4cd00-e544-11e9-9dc0-0076005a1ae0.png)

### Secret
![image](https://user-images.githubusercontent.com/37016180/66034615-885f6200-e544-11e9-933a-f05017ed807c.png)

**Comment by cryptozeny** [comment]
all good. closing.

**Comment by nao20010128nao** [comment]
okay

**Comment by nao20010128nao** [comment]
related: https://github.com/nao20010128nao/WalletGenerator.net/commit/943f26c32c06c21c12127f4d94a4ed80480d4c57
